# Generated by Django 5.1.2 on 2024-12-31 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='typ',
            field=models.CharField(default='action', max_length=200),
        ),
    ]
