# Generated by Django 5.1.2 on 2025-01-01 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Movies_app', '0002_movie_typ'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default='noimg.jpg', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='typ',
            field=models.CharField(default='Action', max_length=200),
        ),
    ]
